import type { Metadata } from 'next'
import { Oswald, Raleway, Rozha_One } from 'next/font/google'
import './globals.css'

const oswald = Oswald({ 
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-oswald'
})

const raleway = Raleway({ 
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-raleway'
})

const rozhaOne = Rozha_One({ 
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-rozhaOne'
})

export const metadata: Metadata = {
  title: 'Void Tattoo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${raleway.variable} ${rozhaOne.variable}`}>
        {children}
      </body>
    </html>
  )
}
